### Lista de todos los usuarios
GET http://localhost:3000/users

### Buscar usuario por id
GET http://localhost:3000/users/3

### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "test Bauch",
    "username": "jalvarenga",
    "email": "juan@unah.hn",
    
    "role": "admin"
}