GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Juan Alvarenga",
    "email":"jperez@unah.edu.hn"
}

###  
GET http://localhost:3000/fwjehfjb

###
